version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/tasks"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
